
on: [ push, pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-13", "macos-14"]

    runs-on: ${{ matrix.os }} 

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        make FLAGS="-O2 -s -Wall"

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        if-no-files-found: error
        name: ${{ matrix.os }}-vhp_huffman.h
        path: src/tbl/vhp_huffman.h
